### ISSUE TITLE
Array index out of range Exception in CitizenManager.SimulationStepImpl(Int32 subStep)

### ISSUE THREAD

**Issue by originalfoo** [keallu/CSL-BulldozeIt#1]
Not sure if this is related to your mod, but @krzychu124 found that Bulldoze It was spamming log with errors - see: https://github.com/CitiesSkylinesMods/TMPE/issues/817#issuecomment-626237737

**Comment by keallu** [comment]
Well, it doesn't happen when I'm testing with Bulldoze It! so it is properly related to an earlier version of TMPE.

Bulldoze It! doesn't make any calls by CitizenManager, neither directly or by reflection, so I guess @krzychu124 might have read the logs wrong.

**Comment by krzychu124** [comment]
Yeah, probably outdated and not even related to `Bulldoze It` (combination of other problems) 😉

**Comment by keallu** [comment]
No worries. I know how it is :) Have a great weekend, @krzychu124 :)

**Comment by krzychu124** [comment]
I've seen a lot of `output_log.txt`'s in the past and some of you mods were mentioned as catching object reference eg:
`[Render It!] ModUtils:PatchOptionsGraphicsPanel -> Exception: Object reference not set to an instance of an object`
I'm not sure if still occurs, might be worth checking as I noticed you've already updated a few of your mods recently ([paradox forums Sep 2021](https://forum.paradoxplaza.com/forum/threads/cities-skylines-steam-object-reference-not-set-to-an-instance-of-an-object-system-nullreferenceexception-details-no-details.1490874/)).

Have a great weekend, @keallu :)

**Comment by keallu** [comment]
Yes, I know Render It! needs a review of a couple of things. I hope to do it soon.
