### ISSUE TITLE
A question,

### ISSUE THREAD

**Issue by Yoon0117** [keallu/CSL-BulldozeIt#2]
Hello, I wanted to use this mod in Epic Games CS, but the steam workshop downloader stopped working, so I wondered if I could use the Source Code to make the .dll file somehow, and use it.

please answer Thank You!

**Comment by keallu** [comment]
Yes, just clone repo or download as zip and build with Visual Studio. That should do it.

**Comment by Yoon0117** [comment]
Ok, Thank you for a quick response! (Usually it takes around a week or two lol)

**Comment by Yoon0117** [comment]
Just tries doing it and failed (its my first time and im noob at VS)

do you have the dll version of the BulldozeIt file that i might be able to use? If you dont, Ill just try to find another way of doing it

**Comment by Yoon0117** [comment]
Also, I can't figure out how to build a DLL file...
Can you help me I rly need this mod

**Comment by Yoon0117** [comment]
Thank you for the response

I don't really know much about Visual Studio and building a DLL, can you please help me with maybe a few steps? Thank you (I have Visual Studio installed)

**Comment by Yoon0117** [comment]
Or do you have the BulldozeIt.dll file that I can use?

**Comment by keallu** [comment]
There are various ways to download mods from the Steam workshop. Just google it. Here you can find the .dll.

**Comment by Yoon0117** [comment]
![image](https://user-images.githubusercontent.com/90393596/178402812-1d0e802c-873b-417a-b87a-0a95f14072fd.png)
I can't use the downloader on this mod. It doesn't say file downloaded before :(

**Comment by Yoon0117** [comment]
by any chance do you own the .dll file yourself?

**Comment by Yoon0117** [comment]
https://www.nexusmods.com/citiesskylines/
in this site i cant find bulldozeit mod
